apiVersion: apps/v1
kind: Deployment
metadata:
  name: douyin-gateway
  labels:
    app: gateway-gin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway-gin
  template:
    metadata:
      labels:
        app: gateway-gin
        version: v1
    spec:
      containers:
        - name: douyin-gateway
          image: ccr.ccs.tencentyun.com/douyin-test/gateway-gin:v1.2
          imagePullPolicy: Always
          resources:
            limits:
              memory: 200Mi
              cpu: "0"
          ports:
            - containerPort: 8080
          env:
            - name: USER_SERVICE_RESOLVER
              value: "dns:///user-balance-svc:8080"
            - name: RELATION_SERVICE_RESOLVER
              value: "dns:///relation-balance-svc:8080"
            - name: FEED_SERVICE_RESOLVER
              value: "dns:///feed-balance-svc:8080"
            - name: FAVORITE_SERVICE_RESOLVER
              value: "dns:///favorite-balance-svc:8080"
            - name: COMMENT_SERVICE_RESOLVER
              value: "dns:///comment-balance-svc:8080"
            - name: PUBLISH_SERVICE_RESOLVER
              value: "dns:///publish-balance-svc:8080"

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-balance-svc
  labels:
    name: gateway-balance-svc
spec:
  ports:
  - name: http-gin
    port: 8080
    targetPort: 8080
  selector:
    app: gateway-gin
