apiVersion: apps/v1
kind: Deployment
metadata:
  name: douyin-feed
  labels:
    app: feed-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: feed-server
  template:
    metadata:
      labels:
        app: feed-server
        version: v1
    spec:
      containers:
        - name: douyin-feed
          image: ccr.ccs.tencentyun.com/douyin-test/feed-srv:v1.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 200Mi
              cpu: "0"
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: "113.54.157.200"
            - name: MYSQL_PORT
              value: "3307"

---
apiVersion: v1
kind: Service
metadata:
  name: feed-balance-svc
  labels:
    name: feed-balance-svc
spec:
  #type: NodePort
  ports:
  - name: grpc-feed
    port: 8080
    targetPort: 8080
  clusterIP: None
  selector:
    app: feed-server
